darkrenaissance/darkfi

.gitignore, lisp/README.md, lisp/TODO.md, scripts/compile_export_rust.py, src/bin/darkfid.rs, src/bin/jubjub.rs, src/bin/mimc.rs, src/bin/mint.rs, src/bin/tutorial.rs, src/bin/zkvm.rs, src/error.rs, src/lib.rs, src/net/message_subscriber.rs, src/old/bits.rs, src/old/mint2.rs, src/old/zkmimc.rs, src/rpc/adapter.rs, src/service/reqrep.rs, src/system/subscriber.rs, src/vm.rs, src/vm_serial.rs, src/wallet/mod.rs, src/wallet/walletdb.rs
For best and standard practices in Rust, acronyms should be CamelCase,
and capitalization should be avoided; i.e. ZKCircuit -> ZkCircuit
This commit replaces all such occurencies in the codebase.
=> Code linting

src/serial.rs
use const generics for [u8; N] array codec impls
=> feat: use const generics for array types

book/src/tutorial.md
Pointing sollet URL to https://www.sollet.io instead of sollet.io which points to https://darkrenaissance.github.io/darkfi/sollet.io which is nowhere.
=> book/tutorial: fixing url

bin/dao-cli/src/main.rs, bin/daod/src/main.rs, bin/ircd/src/main.rs, bin/ircd/src/program_options.rs, src/cli/cli_config.rs, src/cli/cli_parser.rs, src/cli/mod.rs
fixing deprecation of `clap_app!` using clap version 3.0.7 which is used by other binaries in `bin/`
fixing logs filtering in `ircd`
=> bin/ircd: update & fix clap app deprication and log configuration

doc/src/zkas/bincode.md
This pull request introduces a minimal, but workable reference to `zkas` data types, opcodes, and built-in opcode wrappers.
=> `doc/zkas/`: add syntax reference

doc/src/misc/hashchain/hashchain.md, doc/src/misc/hashchain/network_protocol.md
This PR proposes to improve the markdown syntax and readability of the hashchain/hashchain.md and hashchain/network_protocol.md documentation. Some of the proposed changes include:
- Fix typos.
- Remove trailing spaces.
- Add rust code blocks to enable syntax highlighting in hashchain.md.
- Improve grammar.
- A few of the third-person present tense verbs require the _-s_ suffix. For example:
- "The `View` check the..."
is changed to:
- "The `View` checks the..."
- Punctuation/capitalization.
- Wrap lines at 72 columns (a few of the tables, however, still go over).
- Add link to .png example.
=> Improve hashchain docs

contrib/docker/Dockerfile.debian, contrib/docker/Dockerfile.fedora, contrib/docker/Dockerfile.ubuntu
docker build passed for {debianBuster,fedora37,ubuntu22}_rust1.65
=> docker-remove-old-bins-and-remove-apt-cache

doc/src/testnet/testnet.md
hi, the links in doc/src/testnet/testnet.md are broken,i think they should be (page.md) instead of (testnet/page.md), because the testnet.md page is under testnet directory
=> fix testnet page broken links

contrib/docker/Dockerfile.alpine
Tests coredump root cause found::
warning: dropping unsupported crate type `cdylib` for target `x86_64-unknown-linux-musl`
Fixed by:: RUSTFLAGS="-C target-feature=-crt-static" cargo build ...
Then only apk add ttf-opensans needed.
=> Fix Alpine Dockerfile, builds now OK

bin/faucetd/src/main.rs
Updates db_path to use std::path, as follows:
```rust
let db_path = format!("{}/{}", expand_path(&args.database)?.to_str().unwrap(), args.chain);
```
to:
```rust
let db_path = Path::new(expand_path(&args.database)?.to_str().unwrap()).join(args.chain.clone());
```
=> Faucet path fix

script/research/x3dh/src/main.rs, script/research/x3dh/src/xeddsa.rs
Fixes signature verification after crate downgrade.
Most relevat change was the import:
```rust
use ed25519_dalek::{Signature, SigningKey as Ed25519PublicKey};
```
to
```rust
use ed25519_dalek::{Signature, VerifyingKey as Ed25519PublicKey};
```
Lastly, the `.verify()` method was updated to `verify_strict()` since the latter performs maleability checks (`ed25519-dalek-2.0.0-pre.0/src/verifying.rs:299`)
=> Fix x3dh sig

Makefile
this avoids requiring escalated system privileges to install the binaries.
ref: https://doc.rust-lang.org/cargo/guide/cargo-home.html
=> build: use cargo home as install prefix

src/sdk/src/crypto/ecvrf.rs
Ok, it is actually only one warnings :wink:
=> chore: Fix cargo doc warnings

example/dchat/README.md
The correct link to the tutorial is https://darkrenaissance.github.io/darkfi/learn/dchat/dchat.html
- Fixed outdated link so it no longer gives 404
- Updated folder name from `dchat-seed` to `dchat`
=> [example] fix outdated link and filename in README

src/zkas/constants.rs, src/zkas/decoder.rs
The decode() function panics when the input length is less than 10 bytes in size due to direct magic-number indexing on the vector elements. This check returns an error when the input is too small.
=> zkas: fix index out of bounds panic

src/serial/src/async_lib.rs, src/serial/src/lib.rs, src/zkas/decoder.rs
Fix panic due to unchecked Vec::with_capacity inputs. Also change VecDeque to use the same validation pattern even though it was not directly affected
Add panic regression unit test based on fuzzer input that caused the crash
=> zkas: fix out-of-memory panic

fuzz/honggfuzz/Cargo.toml, fuzz/honggfuzz/src/varint_differential.rs
DarkFi's VarInt struct is meant to be equivalent to the one used by BTC. Most of the source code is extremeley similar. This commit adds very basic tests to ensure equivalence between DarkFi's implementation and the one used by the BTC crate.
The tests included here are quite basic. Future work can expand on the testing done on the deserialized values.
This harness can also be used as as guide or template for future differential fuzzing.
=> fuzz: Add differential fuzzing for BTC VarInt

contrib/dependency_setup.sh
Added sqllite3 dependency for Debian-based systems to dependency_setup.sh.
This dependency must have been added with recent functionality updates.
=> Added sqllite3 dependency for Debian-based systems to dependency_setup.sh

Makefile
Fixed for broken "make install" following recent refactorings.  A mixture of typos and irregular nesting for genev executables.
=> Fixed for broken "make install" following recent refactorings

src/zkas/compiler.rs, src/zkas/parser.rs
Fixed a parser bug where it would pass invalid statements to the compiler which resulted in a panic.
Added error handling in the parser when a semicolon is missing. The error message suggests to the dev to add a semicolon.
Also added more detail to the unreachable()! statement in the compiler so that a darkfi dev can see what the erroneous StatementType was that caused the panic.
Example errror cases:
```
<statement> <statement>;
```
and
```
<statement>
<statement>;
```
To test: remove a semicolon from example/simple.zk and run ./zkas example/simple.zk
=> zkas: Fix compiler panic when semicolons are missing

fuzz/honggfuzz/Cargo.toml, fuzz/honggfuzz/script/generate-binary-corpus.sh, fuzz/honggfuzz/script/generate-zk-corpus.sh, fuzz/honggfuzz/src/zkas_compile.rs
Create a fuzz harness to test the ./zkas binary compilation process. The
whole pipeline is tested: Lexer, Parser, Compiler, Analyzer. This is
performed by copying the relevant code from bin/zkas/src/main.rs.
Testing the entire pipeline like this is not very efficient in terms of
fuzzing cycles but on the other hand it is a quick-and-dirty way to find
results. It also benefits from testing the actual inputs to the binary
in the way it's expecting, rather than checking each of the components
in a piecemeal way using interfaces that aren't expected to be exposed
anyway.
=> fuzz: Add fuzz harness for zkas compilation

src/zkas/parser.rs
Add error handling for the parser logic. Both of these issues were found via fuzzing.
Fix Panic 1: instead of panicking via unwrap() when analyzing the namespace, the parser displays an error message informing the .zk file author that they need to add a namespace.
Fix Panic 2: if the length of the `tokens` vector is 0, the parser now displays an error saying so.
=> zkas: fix panics in Parser

src/zkas/analyzer.rs, src/zkas/parser.rs
These issues were discovered with fuzzing.
Panic 1: It was possible to assign a variable to a function/opcode with
no return type. This caused a index-out-of-bounds panic when the
analyzer attempted to access the first element of an empty vector of
return types. The analyzer now presents an error when a .zk author
attempts to assign a variable to an opcode that has no return types.
Panic 2: There was an index-out-of-bounds panic when performing
verification on Literals that were passed to Opcodes that use Array
types as their arguments. This was fixed by pasting the validation code
from the Variable verfication section which handles Arrays properly.
(Refactoring should be done to reduce duplication here.)
Panic 3: Change the `unimplemented()!` panic macro to error handling that informs …
=> zkas: Fix panics in analyzer

src/util/time.rs
Added checks for division by zero by creating a TimeKeeperSafe struct
=> util: fix division-by-zero panics

src/zk/gadget/less_than.rs, src/zk/gadget/native_range_check.rs, src/zk/vm.rs
[review recommendation: commit-by-commit]
Previously, the `native_range_check` gadget only constrained multiples of
`WINDOW_SIZE`. This fix introduces constraints for chunks shorter than
`WINDOW_SIZE`.
=> `zk::gadgets::native_range_check`: Constrain short chunk

contrib/dependency_setup.sh
Added cmake and libclang-dev to the dependency_setup.sh for Debian/Ubuntu apt distros.  I needed these when building against a vanilla 23.10 Ubuntu installation.   Without these there was a build error while compiling the RandomX dependency.
=> Added cmake and libclang-dev to the dependency_setup.sh

doc/book.toml, doc/src/arch/dao.md, doc/src/crypto/rln.md, doc/src/dev/contrib/contrib.md, doc/src/zkas/examples/sapling.md, doc/src/zkas/examples/voting.md, doc/theme/zkas-highlight.js
- registered zkas as custom language in highlight.js
- i used the syntax highlighting rules in [zk.lang](https://github.com/darkrenaissance/darkfi/blob/master/contrib/zk.lang)
=> Add support for colorizing zkas code samples in darkfi book
