Cargo.lock
Cargo.toml
src/bin/cashierd.rs
src/cli/cli_config.rs
src/client.rs
src/crypto/coin.rs
src/crypto/mod.rs
src/crypto/nullifier.rs
src/error.rs
src/rpc/jsonrpc.rs
src/rpc/websockets.rs
src/service/btc.rs
src/service/eth.rs
src/service/gateway.rs
src/service/sol.rs
src/state.rs
src/util/mod.rs
src/vm.rs
src/wallet/cashierdb.rs

* derive `thiserror::Error` for all error types
* use `#[from]` where applicable

feat: use thiserror for error types

---

README.md
src/bin/darkfid.rs
src/bin/drk.rs
src/client.rs
src/rpc/jsonrpc.rs
src/state.rs
src/tx/mod.rs

error: Adding `InternalError` to handle `encode_without_signature`and handling `host` and `port` errors.

Error handling

---

README.md
src/rpc/rpcserver.rs
src/service/gateway.rs
src/service/sol.rs

Mostly replacing `unwrap()` with `?` or `ok_or_else`.
Update README.md for auto completion until moved to clap_app

Reafactoring and error handling

---

book/src/tutorial.md

Spelling fixes at lines 46, 87, 119, and 198.

Minor typos

---

book/src/zkas/bincode.md

Minor typo

---

src/crypto/loader.rs
src/crypto/mod.rs
src/crypto/proof.rs

Merge imports in `loader.rs`
Replace qualified path with use in `proof.rs`
Adding `loader.rs` to `mod.rs`

crypto: minor cleanup

---

Cargo.lock
bin/cashierd/src/main.rs
bin/darkfid/src/main.rs
bin/drk/src/main.rs
bin/gatewayd/src/main.rs
bin/ircd/Cargo.toml
bin/ircd/src/main.rs
bin/ircd/src/protocol_privmsg.rs
bin/map/src/main.rs
src/cli/cli_config.rs
src/cli/cli_parser.rs
src/cli/mod.rs
src/net/message.rs
src/net/mod.rs
src/net/protocol/protocol_registry.rs

Filtering specific targets in logging system

---

IDEOLOGY.md

Hi all!
Just read the IDEOLOGY text after reading this article <https://dark.fi/insights/the-status-quo.html> and found a few small typography "inaccuracies". 
Feel free to ignore if too nitpicky and thanks to share this extract from the Ocalan body of work (:

ideology: fix typography

---

contrib/dependency_setup.sh

contrib: add setup_pacman() for arch-based deps

---

doc/src/learn/dchat/creating-dchat/ui.md
doc/src/learn/dchat/dchat.md

Although will it be good to add issue #109 to this ?

basic typos

---

README.md
doc/src/SUMMARY.md
doc/src/learn/dchat/deployment/start-run-stop.md
doc/src/misc/ircd/private_message.md

just a rough draft , open for suggestions and edits

Private Chat docs 

---

contrib/docker/Dockerfile.ubuntu

…build worked, but tests fail and last commits even fail to build

Dockerfile for Ubuntu, tested with a commit from October

---

contrib/flake.nix

nix flake: add dashu hash

---

Makefile
contrib/docker/Dockerfile.alpine
contrib/docker/Dockerfile.debian
contrib/docker/Dockerfile.fedora
contrib/docker/Dockerfile.ubuntu

Docker build OK for Ubuntu 22 with rust nightly

add zkas dependency to proofs bin, add/remove binaries in Dockerfiles COPY cmd

---

contrib/docker/Dockerfile.ubuntuARMviaEmulation

Beware, uses emulation, with AMD 24 threads: Building 6047.7s

Add Dockerfile for ARM64 build, builds OK, but is slooooow, not tested

---

doc/src/development/learn.md

The learning guide has an incorrect mention of the element/matrix chat, which is outdated.

Remove element chat and add ircd

---

contrib/dependency_setup.sh
contrib/docker/Dockerfile.alpineARMviaEmulation

Actually my bad, this one is tested with FreeBSD 13.2, openBSD will be added soon

Add FreeBSD dependencies and info how to build

---

contrib/flake.lock
contrib/flake.nix

This fixes flake.nix and introduce the use of crane to create the rust package

Fix flake.nix

---

.gitignore

Add JetBrains `.idea` IDE directory to `.gitignore`.

Ignore JetBrains IDE stuff

---

doc/src/architecture/blockchain.md
doc/src/architecture/consensus.md
doc/src/architecture/smart_contracts.md
doc/src/architecture/tx_lifetime.md
doc/src/tutorial.md

Fix: typos

---

doc/src/development/contributing.md

Added a summary of a recent discussion from the dev meeting, including:
- how to approach learning
- how to find specific tasks
- specialization is a good thing

[book] Add more info for beginners in Contributing

---

script/research/zk/groth16/qap.sage

Add sage code that runs through the Groth16 R1CS --> QAP conversion contained in the article
"R1CS and QAP - From Zero to Hero with Finite Fields & sagemath" https://risencrypto.github.io/R1CSQAP/

[research] add sage implementation of R1CS->QAP

---

src/validator/consensus/pid.rs

Added test f_is_bounded to src/validator/consensus/pid.rs
Test by running:
cargo test --release --all-features f_is_bounded

consensus: add unit test for bounds on f

---

src/event_graph2/util.rs

Force panic rather than perform operations that overflow i64 Add explicit check for division by zero

event_graph2: add basic checks on math

---

src/zkas/parser.rs

These issues were found via fuzzing
Panic 1: If the size of the vector of tokens passed to `check_section_structure` is less than 2, the parser tells the author that there are not enough valid tokens in the section.
Panic 2: Very large values of k will result in integer overflow when the value is larger than the type's MAX_SIZE. This causes the existing k <= 16 check to succeed but it actually shouldn't. In debug/fuzzing
contexts, Rust panics. In production, this will not occur.
Panic 3: If invalid/unimplemented characters appear in an argument to a function, the parser panicked when it hit `unimplemented!()`. Now it tells the author that this character cannot be used in an argument to a function.

zkas: fix more panics in Parser

---

src/zk/gadget/zero_cond.rs

Additionally remove the unused `_z` column from the chip config.

zk/gadget/zero_cond: Simplify ZeroCondChip PLONK gate
